<a href="https://colab.research.google.com/github/rajmishra-dev/python-project/blob/main/BAsic_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Array with Numpy

How to convert list into array..!


In [4]:
import numpy as np
a = np.array([1,2,3,4])
print(a.ndim)
print(type(a))
print(a.size)

1
<class 'numpy.ndarray'>
4


In [6]:
a= np.array([1,2,3])
print(a*2) #2,4,6

[2 4 6]


2D Array...!

In [11]:
b = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(b.size)
print(b.ndim)
print(b.shape)

9
2
(3, 3)


3D Array..!

3D store 2 Matrix

In [15]:
c = np.array([
    [[1,2,3], [4,5,6]],
    [[7,8,9], [9,10,11]]
])
print(c)
print(c.ndim)
print(c.shape)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 9 10 11]]]
3
(2, 2, 3)


In [16]:
z = np.zeros((20,4),dtype=int)
print(z.shape)
print(z.ndim)
print(z)

(20, 4)
2
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [19]:
o = np.ones((5,3),dtype =int)
print(o)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [18]:
f = np.full((3,2),7)
print(f)

[[7 7]
 [7 7]
 [7 7]]


In [20]:
r = np.arange(1,10,2)
print(r)
print(type(r))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [22]:
l = np.linspace(1,5,10) #value between 1 to 10
print(l)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [23]:
random1 = np.random.rand(3,3)#(1,50(3,4))
print(random1)

[[0.84645155 0.13960653 0.13726192]
 [0.60138022 0.02015985 0.96005351]
 [0.34195992 0.60330095 0.01713358]]


4D array

In [24]:
import numpy as np

arr4 = np.ones((2, 3, 4, 5))

print(arr4)
print("Number of dimensions:", arr4.ndim)
print("Shape:", arr4.shape)

[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]
Number of dimensions: 4
Shape: (2, 3, 4, 5)


5D array

In [25]:
import numpy as np

arr5 = np.ones((2, 3, 4, 5, 6))

print(arr5)
print("Number of dimensions:", arr5.ndim)
print("Shape:", arr5.shape)

[[[[[1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]]]


  [[[1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]]]


  [[[1. 1. 1. 1. 1. 